image: "python:3.6-alpine"
stages:
    - test
    - pep8

before_script:
    - pip install -q --no-cache-dir -i https://pypi.doubanio.com/simple -r requirements.txt

test:
    stage: test
    script:
        - coverage run --omit='*/__init__.py' --source='mas_tastypie_api' runtests.py test
        - coverage report

pep8:
    stage: pep8
    script:
        - python -m flake8 'mas_tastypie_api' --exclude */migrations


