# Generated by Django 2.0.5 on 2018-10-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20181011_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='test/images'),
        ),
    ]
